package com.udoolleh.backend.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {
    NOT_FOUND_PATH(HttpStatus.NOT_FOUND, "PATH_001", "NOT FOUND PATH"), // 없는 경로로 요청보낸 경우
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED, "PATH_002", "METHOD NOT ALLOWED"), // POST GET방식 잘못 보낸경우
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "PATH_003", "UNSUPPORTED MEDIA TYPE"),

    AUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED, "AUTH001", " AUTHENTICATION_FAILED."), //중복
    REGISTER_FAILED(HttpStatus.UNAUTHORIZED, "AUTH_001", " AUTHENTICATION_FAILED."), //중복
    LOGIN_FAILED(HttpStatus.NOT_FOUND, "AUTH_002", " LOGIN_FAILED."),
    USER_NICKNAME_DUPLICATED(HttpStatus.FORBIDDEN, "AUTH_003", " USER_NICKNAME_DUPLICATED."),
    INVALID_JWT_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH004", "INVALID_JWT_TOKEN."),

    REQUEST_PARAMETER_BIND_FAILED(HttpStatus.BAD_REQUEST, "REQ_001", "PARAMETER_BIND_FAILED"),

    NOT_FOUND_USER(HttpStatus.NOT_FOUND, "USER_001", "NOT_FOUND_USER"),

    HARBOR_NAME_DUPLICATED(HttpStatus.FORBIDDEN, "HARBOR_001", "HARBOR_NAME_DUPLICATED"),
    NOT_FOUND_HARBOR(HttpStatus.NOT_FOUND, "HARBOR_002", "NOT_FOUND_HARBOR"),
    HARBOR_PERIOD_DUPLICATED(HttpStatus.FORBIDDEN, "HARBOR_003", "HARBOR_OPERATING_TIME_DUPLICATED"),
    NOT_FOUND_HARBOR_TIMETABLE(HttpStatus.NOT_FOUND, "HARBOR_004", "NOT_FOUND_HARBOR_TIMETABLE"),

    REVIEW_DUPLICATED(HttpStatus.FORBIDDEN, "REVIEW_001", "REVIEW_DUPLICATED"),
    NOT_FOUND_REVIEW(HttpStatus.NOT_FOUND, "REVIEW_002", "NOT_FOUND_REVIEW"),

    NOT_FOUND_RESTAURANT(HttpStatus.NOT_FOUND, "RESTAURANT_001", "NOT_FOUND_RESTAURANT"),
    RESTAURANT_DUPLICATED(HttpStatus.FORBIDDEN, "RESTAURANT_002", "RESTAURANT_DUPLICATED"),

    NOT_FOUND_PHOTO(HttpStatus.NOT_FOUND, "PHOTO_001", "NOT_FOUND_PHOTO"),

    MENU_DUPLICATED(HttpStatus.FORBIDDEN, "MENU_001", "MENU_DUPLICATED"),
    NOT_FOUND_MENU(HttpStatus.NOT_FOUND, "MENU_002", "NOT_FOUND_MENU"),

    NOT_FOUND_BOARD(HttpStatus.NOT_FOUND, "BOARD_001", "NOT_FOUND_BOARD"),
    NOT_FOUND_BOARD_COMMENT(HttpStatus.NOT_FOUND, "BOARD_002", "NOT_FOUND_BOARD_COMMENT"),

    TRAVEL_COURSE_DUPLICATED(HttpStatus.FORBIDDEN, "COURSE_001", "TRAVEL_COURSE_DUPLICATED"),
    NOT_FOUND_TRAVEL_COURSE(HttpStatus.FORBIDDEN, "COURSE_002", "NOT_FOUND_TRAVEL_COURSE"),

    NOT_FOUND_LIKES(HttpStatus.NOT_FOUND, "LIKES_001", "NOT_FOUND_LIKES"),
    LIKES_DUPLICATED(HttpStatus.FORBIDDEN, "LIKES_002", "LIKES_DUPLICATED"),

    NOT_FOUND_TRAVEL_PLACE(HttpStatus.NOT_FOUND, "PLACE_001", "NOT_FOUND_TRAVEL_PLACE"),
    TRAVEL_PLACE_DUPLICATED(HttpStatus.FORBIDDEN, "PLACE_002", "TRAVEL_PLACE_DUPLICATED");

    private final String code;
    private final String message;
    private final HttpStatus status;

    ErrorCode(final HttpStatus status, final String code, final String message) {
        this.status = status;
        this.code = code;
        this.message = message;
    }
}
