spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:

  flyway:
    url: jdbc:h2:mem:test
    user: sa
    enabled: true
    baselineOnMigrate: true
    locations: classpath:/db/migration/h2,classpath:/db/migration/mysql

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
