spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/h2

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
